{
 "title": "DeveloperStore API",
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests por minuto",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m])) * 60",
     "legendFormat": "rpm"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 10, "h": 8 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Latencia media",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum[5m])) / sum(rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "segundos"
    }
   ]
  }
 ]
}