{
 "title": "DeveloperStore Sales",
 "refresh": "10s",
 "panels": [
  {
   "title": "Vendas criadas",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(developerstore_sales_created_total)",
     "legendFormat": "criadas"
    }
   ]
  },
  {
   "title": "Vendas atualizadas",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(developerstore_sales_modified_total)",
     "legendFormat": "atualizadas"
    }
   ]
  },
  {
   "title": "Vendas canceladas",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(developerstore_sales_cancelled_total)",
     "legendFormat": "canceladas"
    }
   ]
  },
  {
   "title": "Itens cancelados",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(developerstore_sales_item_cancelled_total)",
     "legendFormat": "itens"
    }
   ]
  }
 ]
}